### ISSUE TITLE
Halloween Movies

### ISSUE THREAD

**Issue by sanjithpk** [zero-to-mastery/Halloween-Hacktoberfest#56]
The navbar on this page isn't proper.

**Comment by MattCSmith** [comment]
I don't see an issue with the Movies Navbar, could you explain a little more?

**Comment by sanjithpk** [comment]
![image](https://user-images.githubusercontent.com/40496139/46413794-5ce24580-c73f-11e8-8b74-0fe19940a8a7.png)
Some of the tabs aren't clickable

**Comment by pavelisp** [comment]
The pumpkin designs tab is disabled as far as I can see...

**Comment by m2paulc** [comment]
Worked on fixing nav a little bit. I was able to remove some errors due to multiple calls on jquery. Although, recipe nav hamburger still not showing.

**Comment by sb39** [comment]
@m2paulc  the hamburgur shows on reducing screen width below 768px

**Comment by m2paulc** [comment]
I concur to what Dmitry has explained. The recipe page might have been fixed from last night's PR.

**Comment by sb39** [comment]
@DmitryVdovichencko  thanks for the noticing, as i think most of the commits are made to landing page, which lead to the issue. Also there is not proper responsiveness still to the index file navbar

@m2paulc  the navbar still doesnot work on the recipies, facts, pumpkins design and books page .

**Comment by m2paulc** [comment]
On i understand now. Maybe we can just stay at bootstrap 4.0 to streamline jquery calls. Jquery and bootstrap is needs to be on the html pages for nav to work on mobile views, without them the collapsible nav doesn't work on mobile. Will PR latest change.

**Comment by ashishcodes4** [comment]
Hey if this is still not done, I would love to take a lead on this. 
Let me know if no one is working on this I can have a quick look at it.

**Comment by sb39** [comment]
@ashishcodes4 you can work on it :1:

**Comment by ashishcodes4** [comment]
Hey sorry, did not get notified about the comment. 
I will get working on this.
Lets see!

**Comment by sb39** [comment]
@MattCSmith  is it the time to close this issue ?
